<?php
// One-time importer for OSNOVA users. Reads auth/osnova_users_pending.json
// (generated by extract_osnova_users.py) and creates each user with
// username = password = email and osnova_synced = true. Skips users that
// already exist.
//
// Two ways to run it:
//
//   1) From the browser (admin only):
//        https://sqb-mahalla.uz/scripts/import_osnova_users.php
//      Log in as admin first; you'll see a plain-text progress report.
//
//   2) From the command line (SSH or cPanel Terminal):
//        php scripts/import_osnova_users.php

require_once __DIR__ . '/../auth/lib.php';

$is_cli = PHP_SAPI === 'cli';

if (!$is_cli) {
    sqb_require_admin_page();
    header('Content-Type: text/plain; charset=utf-8');
    header('Cache-Control: no-store');
    // Disable web-server buffering so progress is visible in the browser.
    @ini_set('zlib.output_compression', '0');
    @ini_set('output_buffering', '0');
    @ini_set('implicit_flush', '1');
    while (ob_get_level() > 0) ob_end_flush();
    ob_implicit_flush(true);
}

// Long-running script — bulk hashing 1000+ passwords with bcrypt takes
// minutes. Disable PHP timeouts and don't abort on user disconnect.
@set_time_limit(0);
@ini_set('max_execution_time', 0);
@ini_set('memory_limit', '512M');
ignore_user_abort(true);

// Lower bcrypt cost for bulk import — still secure (industry-standard 10)
// but ~4x faster than cost 12 used for interactively-created accounts.
const BULK_BCRYPT_COST = 10;

$json_path = __DIR__ . '/../auth/osnova_users_pending.json';
if (!file_exists($json_path)) {
    $msg = "Error: $json_path not found.\nRun scripts/extract_osnova_users.py first, then upload the JSON file to the server.\n";
    if ($is_cli) fwrite(STDERR, $msg); else echo $msg;
    exit(1);
}

$raw   = file_get_contents($json_path);
$users = json_decode($raw, true);
if (!is_array($users)) {
    $msg = "Error: invalid JSON in $json_path\n";
    if ($is_cli) fwrite(STDERR, $msg); else echo $msg;
    exit(1);
}

$total = count($users);

function out(string $msg) {
    echo $msg;
    @flush();
}

out("OSNOVA bulk import\n");
out(str_repeat('=', 50) . "\n");
out("Source: auth/osnova_users_pending.json\n");
out("Total users to process: $total\n");
out("Bcrypt cost: " . BULK_BCRYPT_COST . " (faster than interactive cost 12)\n\n");

$started = microtime(true);
$stats   = ['ok' => 0, 'exists' => 0, 'failed' => 0];
$errors  = [];

foreach ($users as $i => $u) {
    $email = strtolower(trim($u['email'] ?? ''));
    if (!$email) {
        $stats['failed']++;
        $errors[] = "row #$i: missing email";
        continue;
    }

    $extra = [
        'osnova_synced' => true,
        'fio'           => $u['fio']        ?? '',
        'region'        => $u['region']     ?? '',
        'department'    => $u['department'] ?? '',
        'position'      => $u['position']   ?? '',
        'bank'          => $u['bank']       ?? '',
        'local_code'    => $u['local_code'] ?? '',
    ];

    // username = email, password = email (matches OSNOVA's existing scheme)
    $r = sqb_user_create($email, $email, 'user', $extra, BULK_BCRYPT_COST);

    if ($r['ok']) {
        $stats['ok']++;
    } elseif ($r['error'] === 'user_exists') {
        $stats['exists']++;
    } else {
        $stats['failed']++;
        $errors[] = "$email: " . $r['error'];
    }

    // Progress every 25 users.
    $done = $i + 1;
    if ($done % 25 === 0 || $done === $total) {
        $pct  = round($done / $total * 100, 1);
        $secs = max(0.1, microtime(true) - $started);
        $rate = $done / $secs;
        $eta  = ($total - $done) / max(0.01, $rate);
        out(sprintf(
            "  [%5d / %5d  %5.1f%%]  ok:%-4d  exists:%-4d  failed:%-3d   %5.1f users/s  ETA: %ds\n",
            $done, $total, $pct, $stats['ok'], $stats['exists'], $stats['failed'], $rate, (int)$eta
        ));
    }
}

$elapsed = microtime(true) - $started;

sqb_audit_log('OSNOVA_BULK_IMPORT', [
    'imported' => $stats['ok'],
    'existed'  => $stats['exists'],
    'failed'   => $stats['failed'],
    'elapsed'  => round($elapsed, 1) . 's',
]);

out("\n" . str_repeat('=', 50) . "\n");
out("Done in " . round($elapsed, 1) . " seconds.\n\n");
out("  Imported:                {$stats['ok']}\n");
out("  Already existed (skipped): {$stats['exists']}\n");
out("  Failed:                  {$stats['failed']}\n");

if ($errors) {
    out("\nErrors (first 20):\n");
    foreach (array_slice($errors, 0, 20) as $e) out("  - $e\n");
    if (count($errors) > 20) out("  ... and " . (count($errors) - 20) . " more\n");
}

out("\nNext steps:\n");
out("  1. Test SSO with one of the imported emails (e.g. xyuldashev@sqb.uz / xyuldashev@sqb.uz)\n");
out("  2. Delete auth/osnova_users_pending.json from the server when satisfied\n");
out("  3. Optionally rename or delete this script to prevent re-runs\n");
